### ISSUE TITLE
"Unexpected token '?'" error while trying to convert a file

### ISSUE THREAD

**Issue by sylvaticus** [opendevise/downdoc#15]
Just installed with `npm i downdoc` on Ubuntu 22.04 and got the following error on my attempt co convert an asciidoc file to markdown:

```
$ npx downdoc ch01-GettingStarted.adoc 
/home/lobianco/node_modules/downdoc/lib/cli.js:22
  const inputPath = positionals[0] ?? (values.postpublish || values.prepublish ? 'README.adoc' : undefined)
                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lobianco/node_modules/downdoc/bin/downdoc:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by sylvaticus** [comment]
worked, sorry I was using a very old version of node...
